version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - "5672:5672"
        - "15672:15672"
  publisher:
    build:
      context: .
      dockerfile: docker/publisher/Dockerfile
    depends_on:
      - "rabbitmq"
  consumer:
    build:
      context: .
      dockerfile: docker/consumer/Dockerfile
    depends_on:
      - "rabbitmq"
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - 8000:8000
  grpc:
    build:
      context: .
      dockerfile: docker/grpc/Dockerfile
    ports:
      - 9000:9000