version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  consumer:
    build:
      context: .
      dockerfile: docker/consumer/Dockerfile
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - 8000:8000